/* Species data is kept separate from the interface so the field guide can grow easily. */
const SPECIES_DATA = {
  birds: {
    label: "Birds", emoji: "🐦", title: "Birds with stories to tell.",
    description: "From tiny garden visitors to ocean-crossing wanderers, meet the remarkable birds that fill our skies.",
    intro: "Feathers, flight, and remarkable journeys",
    image: "photo-1444464666168-49d633b86797",
    items: [
      ["Eagle","Aquila chrysaetos","North America, Europe, Asia","Mountains, grassland","Carnivore","20–30 years","Golden eagles can spot prey from great distances and ride warm air currents to soar."],
      ["Parrot","Psittaciformes","South America, Africa, Asia","Tropical forest","Seeds, fruit, nuts","20–80 years","Many parrots use their strong curved beaks like a third foot when climbing."],
      ["Peacock","Pavo cristatus","South Asia","Forest, grassland","Seeds, insects, plants","10–25 years","A peacock's spectacular train is made of long tail-coverts with eye-like markings."],
      ["Penguin","Spheniscidae","Antarctica, Southern Hemisphere","Ocean, coast","Fish, krill, squid","15–20 years","Penguins' dense, waterproof feathers and blubber help them stay warm in cold seas."],
      ["Owl","Strigiformes","Worldwide","Forest, grassland, wetlands","Carnivore","5–25 years","Soft-edged flight feathers help many owls fly almost silently."],
      ["Sparrow","Passeridae","Worldwide","Grassland, woodland, cities","Seeds, insects","3–5 years","House sparrows have lived alongside people for thousands of years."],
      ["Flamingo","Phoenicopteridae","Africa, Asia, Europe, Americas","Wetlands, lagoons","Algae, tiny crustaceans","20–30 years","Their pink feathers come from pigments in the algae and tiny animals they eat."],
      ["Ostrich","Struthio camelus","Africa","Desert, grassland","Plants, seeds, insects","30–40 years","Ostriches are the world's largest living birds and can sprint at remarkable speed."],
      ["Crow","Corvus","Worldwide","Forest, farmland, cities","Omnivore","7–20 years","Crows can recognize human faces and solve clever food puzzles."],
      ["Kingfisher","Alcedinidae","Worldwide","Rivers, lakes, wetlands","Fish, insects","6–10 years","A kingfisher's long bill helps it make precise dives for fish."],
      ["Hummingbird","Trochilidae","The Americas","Tropical forest, gardens","Nectar, insects","3–12 years","Hummingbirds can hover and fly backwards thanks to unusually flexible wings."],
      ["Toucan","Ramphastidae","Central and South America","Tropical forest","Fruit, insects, eggs","15–20 years","A toucan's large bill is light and helps it reach fruit on slender branches."],
      ["Swan","Cygnus","Europe, Asia, Americas, Australia","Wetlands, lakes","Aquatic plants, insects","10–20 years","Swans have long necks that help them reach plants beneath the water."],
      ["Crane","Gruidae","Every continent except Antarctica","Wetlands, grassland","Plants, insects, small animals","20–30 years","Some crane species migrate thousands of kilometres between seasons."],
      ["Albatross","Diomedeidae","Southern Ocean, North Pacific","Open ocean, coasts","Squid, fish","40–60 years","Albatrosses glide over waves for hours, using wind to travel with very little effort."],
      ["Falcon","Falco","Worldwide","Cliffs, grassland, cities","Carnivore","10–20 years","The peregrine falcon is the fastest animal in a hunting dive."],
      ["Pelican","Pelecanus","All continents except Antarctica","Coasts, lakes, wetlands","Fish","15–25 years","A pelican's expandable throat pouch works like a net for scooping up fish."],
      ["Woodpecker","Picidae","Worldwide except Australia and Antarctica","Forest, woodland","Insects, sap, fruit","4–12 years","Strong skulls and specialised feet help woodpeckers forage on tree trunks."],
      ["Macaw","Ara","Central and South America","Tropical forest","Seeds, nuts, fruit","30–60 years","Macaws can crack very hard nuts with their powerful beaks."],
      ["Emu","Dromaius novaehollandiae","Australia","Grassland, open woodland","Plants, insects","10–20 years","The emu is Australia's tallest native bird and cannot fly."],
      ["Kiwi","Apteryx","New Zealand","Forest, grassland","Worms, insects, fruit","25–50 years","Kiwis have nostrils at the tip of their bill and use smell to find food."],
      ["Pigeon","Columba livia","Worldwide","Cliffs, cities","Seeds, grains","3–15 years","People have kept and bred pigeons for thousands of years."],
      ["Turkey","Meleagris gallopavo","North America","Forest, grassland","Seeds, insects, plants","3–10 years","Wild turkeys can fly short distances despite their heavy-looking bodies."]
    ]
  },
  animals: {
    label: "Animals", emoji: "🦁", title: "Wild lives, wonderful worlds.",
    description: "Meet the mammals, reptiles, amphibians and sea creatures that make every corner of Earth extraordinary.",
    intro: "Big personalities, extraordinary habitats",
    image: "photo-1564349683136-77e08dba1ef7",
    items: [
      ["Lion","Panthera leo","Africa, India","Grassland, savanna","Carnivore","10–18 years","Lions are the only big cats that naturally live in social groups called prides."],
      ["Tiger","Panthera tigris","Asia","Forest, grassland, wetlands","Carnivore","10–15 years","Every tiger has a unique stripe pattern, like a fingerprint."],
      ["Elephant","Elephantidae","Africa, Asia","Savanna, forest","Herbivore","60–70 years","Elephants use their trunks to smell, breathe, drink, communicate and pick up tiny objects."],
      ["Giraffe","Giraffa","Africa","Savanna, woodland","Herbivore","20–25 years","A giraffe's spots help it blend in, and no two patterns are exactly alike."],
      ["Zebra","Equus","Africa","Grassland, savanna","Herbivore","20–30 years","Each zebra has its own unique pattern of black and white stripes."],
      ["Bear","Ursidae","North America, Europe, Asia","Forest, mountains, Arctic","Omnivore","20–30 years","Bears have an excellent sense of smell that helps them locate food."],
      ["Wolf","Canis lupus","North America, Europe, Asia","Forest, tundra, grassland","Carnivore","6–8 years","Wolves communicate using howls, scent marks, facial expressions and body language."],
      ["Fox","Vulpes","Worldwide","Forest, grassland, desert, cities","Omnivore","3–6 years","Foxes use the Earth's magnetic field to help them pinpoint prey under snow."],
      ["Deer","Cervidae","Worldwide except Antarctica","Forest, grassland","Herbivore","10–20 years","Most deer grow and shed a fresh set of antlers each year."],
      ["Horse","Equus caballus","Worldwide","Grassland, domesticated","Herbivore","25–30 years","People and horses have worked together for thousands of years."],
      ["Dog","Canis lupus familiaris","Worldwide","Many habitats, alongside people","Omnivore","10–13 years","Dogs were among the first animals people domesticated, more than 15,000 years ago."],
      ["Cat","Felis catus","Worldwide","Many habitats, alongside people","Carnivore","12–18 years","Domestic cats share a common ancestor with the African wildcat."],
      ["Gorilla","Gorilla","Central Africa","Tropical forest, mountains","Herbivore","35–40 years","Gorillas live in close-knit family groups led by a silverback."],
      ["Chimpanzee","Pan troglodytes","Central and West Africa","Tropical forest, woodland","Omnivore","30–40 years","Chimpanzees make and use tools, including sticks to gather insects."],
      ["Kangaroo","Macropus","Australia","Grassland, woodland","Herbivore","8–23 years","A young kangaroo, called a joey, continues growing in its mother's pouch."],
      ["Panda","Ailuropoda melanoleuca","China","Mountain forest","Herbivore","15–20 years","Giant pandas eat bamboo for many hours each day."],
      ["Cheetah","Acinonyx jubatus","Africa, Iran","Grassland, savanna","Carnivore","10–12 years","A cheetah's flexible spine helps it take very long strides while running."],
      ["Leopard","Panthera pardus","Africa, Asia","Forest, grassland, mountains","Carnivore","12–17 years","Leopards are powerful climbers and often carry food up into trees."],
      ["Rhinoceros","Rhinocerotidae","Africa, Asia","Grassland, forest","Herbivore","35–50 years","A rhino's horn is made of keratin, the same material as human hair and nails."],
      ["Hippopotamus","Hippopotamus amphibius","Sub-Saharan Africa","Rivers, wetlands, grassland","Herbivore","40–50 years","Hippos spend the day in water and come ashore to graze at night."],
      ["Camel","Camelus","Africa, Asia","Desert, dry grassland","Herbivore","40–50 years","A camel's hump stores fat, which can be used for energy when food is scarce."],
      ["Koala","Phascolarctos cinereus","Australia","Eucalyptus forest","Herbivore","10–15 years","Koalas eat eucalyptus leaves, which few other mammals can safely digest."],
      ["Sloth","Folivora","Central and South America","Tropical forest","Herbivore","20–30 years","Algae can grow on a sloth's fur, helping it blend into the treetops."],
      ["Whale","Cetacea","All oceans","Ocean","Carnivore","20–90 years","Whales are mammals: they breathe air, give birth to live young and feed them milk."],
      ["Dolphin","Delphinidae","Worldwide oceans","Ocean, coastal waters","Carnivore","20–60 years","Dolphins use clicks and whistles to communicate and navigate underwater."],
      ["Crocodile","Crocodylidae","Africa, Asia, Australia, Americas","Rivers, wetlands","Carnivore","35–75 years","Crocodiles have been part of Earth's ecosystems for more than 80 million years."],
      ["Alligator","Alligatoridae","North America, China","Wetlands, rivers","Carnivore","35–50 years","Alligators make 'gator holes' that can provide water for other animals in dry seasons."],
      ["Snake","Serpentes","Worldwide except Antarctica","Forest, desert, grassland","Carnivore","5–30 years","Snakes smell by collecting scent particles with their forked tongues."],
      ["Turtle","Testudines","Oceans, rivers, land","Ocean, wetlands","Omnivore","20–100+ years","Sea turtles navigate long migrations and return to nesting regions."],
      ["Tortoise","Testudinidae","Africa, Asia, Americas","Desert, grassland","Herbivore","50–150+ years","A tortoise's shell is part of its skeleton and grows with it."],
      ["Chameleon","Chamaeleonidae","Africa, Madagascar, Asia","Forest, scrubland","Insectivore","2–10 years","Chameleons can move their eyes independently to look in two directions."],
      ["Komodo Dragon","Varanus komodoensis","Indonesia","Tropical forest, savanna","Carnivore","20–30 years","Komodo dragons are the largest living lizards."],
      ["Frog","Anura","Worldwide except Antarctica","Wetlands, forest, grassland","Insectivore","2–15 years","Most frogs begin life as tadpoles and change dramatically as they grow."],
      ["Toad","Bufonidae","Worldwide except Antarctica","Forest, grassland, gardens","Insectivore","5–15 years","Toads have dry, bumpy skin and help control insect populations."],
      ["Salamander","Caudata","North America, Europe, Asia","Forest, wetlands","Insectivore","5–20 years","Some salamanders can regrow lost limbs."],
      ["Shark","Selachimorpha","All oceans","Ocean","Carnivore","20–70 years","Sharks have existed for more than 400 million years."],
      ["Octopus","Octopoda","Worldwide oceans","Ocean, coral reef","Carnivore","1–5 years","An octopus has three hearts, blue blood and remarkable camouflage."],
      ["Jellyfish","Scyphozoa","Worldwide oceans","Ocean","Carnivore","A few hours–years","Jellyfish have no brain, heart or bones, yet they have lived in oceans for millions of years."],
      ["Seahorse","Hippocampus","Worldwide, mainly tropical","Ocean, seagrass beds","Small crustaceans","1–5 years","Seahorses are unusual because the male carries developing young in a pouch."],
      ["Starfish","Asteroidea","Worldwide oceans","Ocean, seafloor","Omnivore","5–35 years","Sea stars can regrow some lost arms, and many have tiny tube feet underneath."],
      ["Polar Bear","Ursus maritimus","Arctic","Arctic, ocean ice","Carnivore","20–25 years","Polar bears have black skin beneath their light-coloured fur."],
      ["Sea Otter","Enhydra lutris","North Pacific","Ocean, coastal kelp forests","Carnivore","10–20 years","Sea otters use tools, such as rocks, to open shellfish."],
      ["Platypus","Ornithorhynchus anatinus","Australia","Rivers, freshwater","Carnivore","10–17 years","The platypus is a mammal that lays eggs and senses prey with its bill."]
    ]
  },
  trees: {
    label: "Trees", emoji: "🌳", title: "Rooted in remarkable stories.",
    description: "Meet the towering elders, tiny-seeded pioneers and everyday trees that quietly shape life on Earth.",
    intro: "Deep roots, long memories, living legacies",
    image: "photo-1448375240586-882707db888b",
    items: [
      ["Banyan Tree","Ficus benghalensis","South Asia","Tropical forest, gardens","60–100 ft","200–500+ years","Shade, shelter, food, cultural importance","A banyan can send roots down from its branches, creating many trunk-like supports."],
      ["Neem Tree","Azadirachta indica","South Asia","Tropical, dry regions","50–65 ft","150–200 years","Shade, timber, traditional uses","Neem has been valued in South Asian communities for centuries."],
      ["Mango Tree","Mangifera indica","South Asia","Tropical forest, gardens","30–100 ft","100–300 years","Fruit, shade, timber","Mango has been cultivated in South Asia for thousands of years."],
      ["Coconut Palm","Cocos nucifera","Indo-Pacific tropics","Tropical coast, islands","50–100 ft","60–100 years","Food, fibre, building materials","Coconuts can float, helping the palm spread to distant tropical shores."],
      ["Oak","Quercus","Northern Hemisphere","Forest, woodland","40–100 ft","200–1,000 years","Timber, wildlife habitat, shade","Oak trees support hundreds of kinds of insects and other wildlife."],
      ["Maple","Acer","Asia, Europe, North America","Forest, woodland","30–100 ft","100–400 years","Timber, shade, maple syrup","The maple leaf is a national symbol of Canada."],
      ["Pine","Pinus","Northern Hemisphere","Forest, mountains","15–250 ft","100–1,000+ years","Timber, paper, resin, habitat","Pine seeds are protected inside woody cones."],
      ["Redwood","Sequoia sempervirens","California, United States","Coastal temperate forest","200–380 ft","1,000–2,000+ years","Carbon storage, habitat, timber","Coast redwoods are among the tallest trees on Earth."],
      ["Baobab","Adansonia","Africa, Madagascar, Australia","Savanna, dry tropical woodland","15–100 ft","1,000+ years","Food, water storage, shelter","Some baobabs store water in their thick trunks and live for over a thousand years."],
      ["Eucalyptus","Eucalyptus","Australia","Forest, woodland","30–300 ft","50–500 years","Timber, paper, habitat","Eucalyptus leaves are the main food of koalas."],
      ["Teak","Tectona grandis","South and Southeast Asia","Tropical forest","100–130 ft","100–200 years","Durable timber, furniture, boats","Teak's naturally oily wood is especially durable."],
      ["Cedar","Cedrus","Himalayas, Mediterranean","Mountains, forest","100–200 ft","200–1,000 years","Timber, cultural heritage, habitat","Cedar wood was prized for building in ancient Mediterranean societies."],
      ["Birch","Betula","Europe, Asia, North America","Forest, woodland","30–70 ft","60–100 years","Paper, timber, wildlife habitat","Birch bark has been used to make containers and canoes."],
      ["Olive Tree","Olea europaea","Mediterranean region","Mediterranean woodland","10–50 ft","300–2,000 years","Olives, oil, shade","People have cultivated olive trees around the Mediterranean for thousands of years."],
      ["Apple Tree","Malus domestica","Central Asia","Temperate forest, orchards","10–30 ft","30–100 years","Fruit, food, pollinator habitat","Modern apples descend from wild ancestors in the mountains of Central Asia."],
      ["Cherry Blossom Tree","Prunus serrulata","East Asia","Temperate woodland, gardens","15–40 ft","15–40 years","Ornamental, cultural tradition, pollinators","Cherry blossom viewing has been a celebrated spring tradition in Japan for centuries."],
      ["Mahogany","Swietenia","Central America, Caribbean","Tropical forest","100–150 ft","350+ years","Timber, habitat, carbon storage","Mahogany's beautiful, durable wood has made it valuable for furniture."],
      ["Rubber Tree","Hevea brasiliensis","Amazon basin","Tropical rainforest","65–130 ft","30–100 years","Natural rubber, livelihoods, shade","Natural rubber tapped from this tree changed transport and manufacturing."],
      ["Bamboo","Poaceae","Asia, Africa, Americas","Tropical, temperate forest","1–100 ft","Several decades","Food, building material, crafts","Some bamboo species grow remarkably quickly and can flower only after many decades."],
      ["Date Palm","Phoenix dactylifera","Middle East, North Africa","Desert oases, arid regions","50–75 ft","100+ years","Dates, shade, fibre","Date palms have supported communities around desert oases for thousands of years."],
      ["Acacia","Acacia","Africa, Australia, Americas","Savanna, dry woodland","15–100 ft","20–100 years","Shade, food, habitat, gum","Some acacias provide food and shelter for ants that help defend the tree."],
      ["Giant Sequoia","Sequoiadendron giganteum","California, United States","Mountain forest","150–300 ft","1,000–3,000+ years","Carbon storage, habitat, conservation","The giant sequoia is among the largest trees on Earth by volume."]
    ]
  },
  plants: {
    label: "Plants", emoji: "🌿", title: "A world of growth and wonder.",
    description: "From helpful herbs to dazzling flowers and essential crops, discover the plants woven into everyday life.",
    intro: "Small seeds, big stories",
    image: "photo-1501004318641-b39e6451bec6",
    items: [
      ["Rose","Rosa","Asia, Europe, North America","Gardens, temperate regions","Ornamental, perfume, food","Perennial","Rose fossils show that the flower family is tens of millions of years old."],
      ["Lotus","Nelumbo nucifera","Asia, Australia","Freshwater wetlands","Food, ornamental, cultural","Perennial","Lotus leaves repel water and dirt, inspiring self-cleaning materials."],
      ["Sunflower","Helianthus annuus","North America","Grassland, farms, gardens","Seeds, oil, pollinator food","Annual","Young sunflowers track the sun across the sky as they grow."],
      ["Tulip","Tulipa","Central Asia","Meadows, gardens","Ornamental, horticulture","Perennial","Tulips became so prized in the Netherlands during the 1600s that they inspired a famous trading boom."],
      ["Jasmine","Jasminum","Asia, Africa, Europe","Tropical and temperate gardens","Fragrance, tea, ornamental","Perennial","Many jasmine flowers release their strongest scent after sunset."],
      ["Lavender","Lavandula","Mediterranean region","Dry, sunny hillsides","Fragrance, pollinators, traditional uses","Perennial","Bees are strongly attracted to lavender's nectar-rich flowers."],
      ["Aloe Vera","Aloe vera","Arabian Peninsula","Desert, dry gardens","Skin-care, ornamental","Perennial succulent","Aloe stores water in its thick leaves, helping it survive dry spells."],
      ["Mint","Mentha","Europe, Asia, Africa","Moist soils, gardens","Food, flavouring, traditional uses","Perennial","Mint spreads through underground stems and grows readily in many gardens."],
      ["Basil","Ocimum basilicum","South Asia, Southeast Asia","Warm gardens, farms","Food, seasoning","Annual","Basil belongs to the mint family and has been grown for thousands of years."],
      ["Fern","Polypodiopsida","Worldwide","Forest, wetlands, shaded places","Ornamental, soil cover, habitat","Perennial","Ferns reproduce with spores rather than flowers or seeds."],
      ["Cactus","Cactaceae","The Americas","Desert, dry regions","Food, water storage, habitat","Long-lived perennial","A cactus's spines are modified leaves that help reduce water loss."],
      ["Venus Flytrap","Dionaea muscipula","North and South Carolina, United States","Wetlands, bogs","Insect capture, conservation","Perennial","Its leaves snap shut when tiny trigger hairs are touched more than once."],
      ["Bamboo","Bambusoideae","Asia, Africa, Americas","Tropical, temperate regions","Food, building, paper","Perennial","Bamboo is a grass, not a tree, and some kinds flower only rarely."],
      ["Water Lily","Nymphaeaceae","Worldwide","Freshwater ponds, lakes","Habitat, ornamental, shade","Perennial","Water lily pads provide shade and shelter for animals in ponds."],
      ["Orchid","Orchidaceae","Worldwide except Antarctica","Tropical forest, grassland","Ornamental, pollinator relationships","Perennial","Orchids are one of the largest and most diverse flowering plant families."],
      ["Dandelion","Taraxacum officinale","Europe, Asia","Meadows, lawns, roadsides","Pollinator food, edible leaves","Perennial","Dandelion seeds travel on parachute-like tufts carried by the wind."],
      ["Wheat","Triticum aestivum","Fertile Crescent","Temperate farms, grassland","Food, flour, animal feed","Annual","Wheat farming began around 10,000 years ago and helped shape settled communities."],
      ["Rice","Oryza sativa","East and Southeast Asia","Wetlands, flooded fields","Food, livelihoods","Annual","Rice is a staple food for more than half of the world's people."],
      ["Cotton","Gossypium","Africa, Asia, the Americas","Warm regions, farms","Fibre, textiles, seed oil","Perennial shrub, often farmed annually","Cotton fibres grow around the seeds of the cotton plant."],
      ["Tea Plant","Camellia sinensis","East Asia","Tropical and subtropical hills","Tea, livelihoods","Evergreen perennial","Green, black and oolong teas can all come from leaves of the same plant."],
      ["Coffee Plant","Coffea","Tropical Africa","Tropical highlands, farms","Coffee, livelihoods","Evergreen perennial","Coffee beans are actually the seeds inside small fruits called coffee cherries."],
      ["Tomato Plant","Solanum lycopersicum","South America","Gardens, farms","Food, nutrition","Perennial, usually farmed annually","Tomatoes originated in the Andes and were domesticated in the Americas."],
      ["Banana Plant","Musa","Southeast Asia","Tropical gardens, farms","Food, fibre, shade","Perennial herb","The banana plant is a giant herb, not a tree, and its berries grow in clusters."]
    ]
  }
};
